### PR TITLE
resolves #3089 fix crash caused by an inline passthrough with the macros sub

### LINKED ISSUE #3089: `block in restore_passthroughs': undefined method `[]' for nil:NilClass (NoMethodError)
#### Reproduction case

```
echo "pass:m[a] stem:[b]" |  ./bin/asciidoctor - --trace
```
```
/path/to/asciidoctor/lib/asciidoctor/substitutors.rb:319:in `block in restore_passthroughs': undefined method `[]' for nil:NilClass (NoMethodError)
	from /path/to/asciidoctor/lib/asciidoctor/substitutors.rb:316:in `gsub'
	from /path/to/asciidoctor/lib/asciidoctor/substitutors.rb:316:in `restore_passthroughs'
	from /path/to/asciidoctor/lib/asciidoctor/substitutors.rb:112:in `apply_subs'
	from /path/to/asciidoctor/lib/asciidoctor/block.rb:112:in `content'
	from /path/to/asciidoctor/lib/asciidoctor/converter/html5.rb:716:in `paragraph'
	from /path/to/asciidoctor/lib/asciidoctor/converter.rb:376:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /path/to/asciidoctor/lib/asciidoctor/document.rb:988:in `content'
	from /path/to/asciidoctor/lib/asciidoctor/converter/html5.rb:176:in `document'
	from /path/to/asciidoctor/lib/asciidoctor/converter.rb:376:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/document.rb:919:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor.rb:1463:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/cli/invoker.rb:106:in `invoke!'
	from ./bin/asciidoctor:15:in `<main>'
```

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #3089

- fix crash caused by inline passthrough macro with the macros sub clearing the remaining passthrough placeholders

### CODE REVIEW

**Comment by Mogztter** [comment]
resolves #3089 (to link the issue and the pull request)

**Comment by mojavelinux** [comment]
I like this new strategy. It's less API invasive...and it works with Opal (as far as I can tell).

**Comment by mojavelinux** [comment]
> (to link the issue and the pull request)

it drives me nuts that GitHub requires that you put the issue number in the comment instead of the title.

File: lib/asciidoctor/substitutors.rb [hunk 1]
```diff
@@ -303,28 +321,19 @@ def extract_inner_passthrough text, pre, attributes = nil
...
     passes = @passthroughs
-    # passthroughs may have been eagerly restored (e.g., footnotes)
-    #if outer && (passes.empty? || !text.include?(PASS_START))
-    #  return text
-    #end
-
     text.gsub PassSlotRx do
       # NOTE we can't remove entry from map because placeholder may have been duplicated by other substitutions
-      pass = passes[$1.to_i]
+      pass = passes[$1.to_i] || PASS_UNRESOLVED
```
Comment (Mogztter) [inline lib/asciidoctor/substitutors.rb]: I don't really like this placeholder value. Is it to avoid code duplication ? 
I guess we could replace it with a condition ? if `passes` is defined then do X else to do Z ?

Comment (mojavelinux) [reply lib/asciidoctor/substitutors.rb]: This should never happen. But in the extreme case that it does (perhaps a misbehaving extension), we just want to avoid a crash. And because it's such an exception, I don't want to waste any time checking if the value is there. (We don't have to use a constant...we could just inline the value).

**Comment by Mogztter** [comment]
> I like this new strategy. It's less API invasive...and it works with Opal (as far as I can tell).

Indeed and the state is "encapsulated" (not just a dangling boolean param)

**Comment by mojavelinux** [comment]
Precisely.

File: lib/asciidoctor/substitutors.rb (hunk 1 above)
Comment (mojavelinux) [reply lib/asciidoctor/substitutors.rb]: Is your issue with the constant or the fallback? If it's just a constant, I can inline it.

I prefer the fallback right now because we need to stop being bitten by this crash and this solves it with the least amount of overhead.

Comment (Mogztter) [reply lib/asciidoctor/substitutors.rb]: It's both. 
As you've mentioned it's unlikely that `passes[$1.to_i]` will equal `{ text: '??pass??' }` but if it happens we won't know for sure if it's the fallback value or not (but that's not my biggest concern)

> And because it's such an exception, I don't want to waste any time checking if the value is there.

Behind the scene Ruby will check if the value is there right ? When you say "I don't want to waste any time checking" you mean at runtime ?
I think it should maybe be a bit faster since we don't need to check `if (type = pass[:type])` if `passes[$1.to_i]` is nil.
Also since we know that `pass[:subs]` will be undefined maybe we can skip this call `subbed_text = apply_subs(pass[:text], pass[:subs])`.

My point is that we execute the same code path but it fells like we should not.

```rb
if (pass = passes[$1.to_i])
  # do X
else
  # do Z 
end
```

**Comment by mojavelinux** [comment]
The last implementation had a measurable impact on performance. I came up with another way by moving the lock variable to the current node. I can confirm this solution has negligible or no impact on performance. (This is a very touchy part of the code).

File: lib/asciidoctor/substitutors.rb (hunk 1 above)
Comment (mojavelinux) [reply lib/asciidoctor/substitutors.rb]: Let me text perf. As I mentioned, this is tough because this code is just hammered to death.

Comment (mojavelinux) [reply lib/asciidoctor/substitutors.rb]: Done. And you'll like that we even log an error now ;)
