### PR TITLE
resolves #3279 process multiple single-item menu macros in single line

### LINKED ISSUE #3279: multiple menu marcos in a paragraph interpreted strangely
When there are multiple single-level menu inline macros in a paragraph, they are wrongly conflated together.

### To reproduce

Place two or more single-level menu entries in the same paragraph.

E.g.
```asciidoc
:experimental:

Click menu:foo[] and then menu:foo[] again.
```

or equivalently on several source lines (but still one target paragraph)

```asciidoc
:experimental:

Click menu:foo[] and
then menu:foo[] again.
```

#### Expected

These are interpreted as separate macros, resulting in e.g. (for the `docbook` backend)
```xml
Click
<guimenu>foo</guimenu>
and then
<guimenu>foo</guimenu>
again.
```

#### Observed

They are interpreted as one macro, with the stuff between them as part of a menu item, e.g (`docbook` again):
```xml
Click
<menuchoice>
  <guimenu>foo</guimenu>
  <guimenuitem>] and then menu:foo[</guimenuitem>
</menuchoice>
again.
```
(linebreaks & indentation added manually, to better show the structure)

<details><summary>click here for the actual result file content</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>Untitled</title>
<date>2019-04-25</date>
</info>
<simpara>Click <menuchoice><guimenu>foo</guimenu> <guimenuitem>] and then menu:foo[</guimenuitem></menuchoice> again.</simpara>
</article>
```

</details>

---

### unaffected

Multi-level menus in either style seem to work alright:

```asciidoc
:experimental:

Click menu:foo[bar] and then menu:foo[bar] again.

Click menu:foo[bar > baz] and then menu:foo[bar > baz] again.

Click "foo > bar" and then "foo > bar" again.

Click "foo > bar > baz" and then "foo > bar > baz" again.
```

As does the similarly structured inline macros `link`:
```asciidoc
Click link:foo[] and then link:foo[] again.

Click link:foo[bar] and then link:foo[bar] again.

Click link:foo[bar,window=baz] and then link:foo[bar,window=baz] again.
```
---
Output of `asciidoctor --version`:
```
Asciidoctor 2.0.8 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
I've tested this with the `asciidoctor/docker-asciidoctor` docker image, sha256 `b72e4a384dbed3a9f24690554d54eeb77039b838b7ed5a2b11b58ed34c248305`.

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #3279

### CODE REVIEW

File: test/substitutions_test.rb [hunk 1]
```diff
@@ -1550,6 +1550,11 @@
         assert_equal %q{<guimenu>File</guimenu>}, para.sub_macros(para.source)
       end
 
+      test 'should process multiple menu macros in same line' do
+        para = block_from_string('menu:File[] and menu:Edit[]', attributes: { 'experimental' => '' })
+        assert_equal '<b class="menuref">File</b> and <b class="menuref">Edit</b>', para.sub_macros(para.source)
+      end
+
```
Comment (das-g) [inline test/substitutions_test.rb]: :+1:
