### PR TITLE
resolves #2622 raise clearer exception when extension class cannot be resolved

### LINKED ISSUE #2622: Report clearer error message if extension class cannot be resolved from string
Under certain circumstances, when a string is passed to an extension registration method, and the extension class cannot be resolved, Asciidoctor allows a low-level Ruby error message to bubble up.

Specifically, if the value is not a valid constant name (e.g., the value starts with a lowercase letter), the exception is not properly caught and, as a result, the user sees a cryptic message.

```rb
Asciidoctor::Extensions.register do
  block 'foobar'
end
```

In this case, since "foobar" begins with a lowercase, the user sees:

```
NameError: wrong constant name foobar
```

This exception should be caught so that the user sees this message instead:

```
Could not resolve class for name: foobar
```

Additionally, the resolver method is finding classes in the top-level scope even if specified with a specific scope:

```rb
class CustomBlockMacro < Asciidoctor::Extensions::BlockMacroProcessor
  use_dsl
  named :foobar
  def process parent, target
    puts %(processing #{target} macro...)
  end
end

Asciidoctor::Extensions.register do
  block_macro 'Asciidoctor::Extensions::CustomBlockMacro'
end
```

The CustomBlockMacro extension should not be resolved.

### PR DESCRIPTION
**Pull request by mojavelinux**
- split impl of class_for_name by Ruby version
- add tests to verify correct error message is thrown when passed an illegal constant name
- add tests to verify top-level class is not resolved when namespaced class is requested

### CODE REVIEW

File: lib/asciidoctor/extensions.rb [hunk 1]
```diff
@@ -1481,17 +1481,36 @@ def resolve_class object
...
-          raise ::NameError, %(Could not resolve class for name: #{qualified_name})
+    if RUBY_MIN_VERSION_2
+      def class_for_name qualified_name
+        resolved = ::Object.const_get qualified_name, false
+        raise unless ::Class === resolved
+        resolved
+      rescue
+        raise ::NameError, %(Could not resolve class for name: #{qualified_name})
+      end
+    elsif RUBY_MIN_VERSION_1_9
```
Comment (Mogztter) [inline lib/asciidoctor/extensions.rb]: Ruby 1.9 is not EOL yet ?

Comment (mojavelinux) [reply lib/asciidoctor/extensions.rb]: Yes. But we need a dedicated release and announcement before we can drop support. Until then, I have to keep the test suite running as is.

**Comment by mojavelinux** [comment]
I know, I was so surprised to find out this is finally built-in as of Ruby 2...and that Opal supports it too.
