### PR TITLE
resolves #4368 redo loop rather than using recursion to locate next line to process

### LINKED ISSUE #4368: Stackoverflow error in reader.rb in Asciidoctor 2.0.17
A user of the AsciiDoc plugin for IntelliJ reported anonymously the following exception via the Sentry error reporter.

I don't know the input that caused this, still I hope this stack trace reals helpful information. 

Looking at the classes this happens with Asciidoctor 2.0.17. 

```
java.lang.StackOverflowError: null
    at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
    at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1229)
    at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_17.lib.asciidoctor.reader.invokeSuper0:peek_line(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/reader.rb:652)
    at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_17.lib.asciidoctor.reader.RUBY$method$peek_line$0(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/reader.rb:652)
    at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
    at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:149)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:148)
    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:142)
    at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_17.lib.asciidoctor.reader.invokeOther15:peek_line(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/reader.rb:137)
    at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_17.lib.asciidoctor.reader.RUBY$method$peek_line$0(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/reader.rb:137)
    at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
    at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1229)
    at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_17.lib.asciidoctor.reader.invokeSuper0:peek_line(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/reader.rb:652)
    at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_17.lib.asciidoctor.reader.RUBY$method$peek_line$0(uri:classloader:/gems/asciidoctor-2.0.17/lib/asciidoctor/reader.rb:652)
```

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

File: lib/asciidoctor/reader.rb [hunk 1]
```diff
@@ -129,16 +129,16 @@ def next_line_empty?
...
+      return @unescape_next_line ? ((line = @lines[-1]).slice 1, line.length) : @lines[-1] if direct || @look_ahead > 0
+      if @lines.empty?
+        @look_ahead = 0
+        return
+      end
       # FIXME the problem with this approach is that we aren't
       # retaining the modified line (hence the @unescape_next_line tweak)
       # perhaps we need a stack of proxied lines
-      (process_line @lines[-1]) || peek_line
+      return (process_line @lines[-1]) || redo
```
Comment (Mogztter) [inline lib/asciidoctor/reader.rb:141]: It seems to be supported in Opal, not sure if the implementation is performant or not, I will give it a try.

Comment (mojavelinux) [reply lib/asciidoctor/reader.rb]: I found a slightly more portable way of doing it that doesn't rely on redo and seems to be even faster.

Comment (Mogztter) [reply lib/asciidoctor/reader.rb]: Perfect 👌🏻

**Review by Mogztter — APPROVED** [review]
