### PR TITLE
resolves #2884 add clearer exception message when input data is binary or has invalid encoding

### LINKED ISSUE #2884: Encoding normalization failure?
One of the first things I immediately saw when starting to test asciidoctor is that it fails to deal with malformed binary data. I don't know if asciidoctor intends to deal with such input at all, but it throws an unhandled `Encoding::InvalidByteSequenceError` Exception when it fails to deal with the input encoding. I think it would be correct to either prevent this from happening or properly handle the exception.

I only examined the first crashes I got in which the exception is raised from `normalize_lines_array` in `helpers.rb`. I did not see any crashes in `normalize_lines_from_string` but my hunch says it also needs some care. 

Since the reference crash files are binary [I uploaded them to gist](https://gist.github.com/zelivans/74bc642add4829975e2e1f77025379e4#file-id-000001-sig-10-src-000076-op-havoc-rep-128). The two top crash lines (full in the gist):

1. 
```
/home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:78:in `encode': asciidoctor: FAILED: /home/ariel/afl-kisaten/private/sandbox/asciidoctor/encoding_crash/id:000000,sig:10,src:000048,op:havoc,rep:128: Failed to load AsciiDoc document - "\xDDc" on UTF-16BE (Encoding::InvalidByteSequenceError)
```

2. 
```
/home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:75:in `encode': asciidoctor: FAILED: /home/ariel/afl-kisaten/private/sandbox/asciidoctor/encoding_crash/id:000001,sig:10,src:000076,op:havoc,rep:128: Failed to load AsciiDoc document - incomplete "t" on UTF-16LE (Encoding::InvalidByteSequenceError)
```

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #2884

### CODE REVIEW

File: lib/asciidoctor.rb [hunk 1]
```diff
@@ -1296,7 +1296,7 @@ def load input, options = {}
       source = input
     elsif ::Array === input
       source = input.drop 0
-    else
+    elsif input
```
Comment (mojavelinux) [inline lib/asciidoctor.rb]: This allows input to be nil. The processor will treat it as an empty document.
