### PR TITLE
resolves #1890 warn if doctype=inline and block has unexpected content model

### LINKED ISSUE #1890: Asciidoctor should issue a warning if there is a block but it's not a candidate for inline conversion
## Current state

``` javascript
var asciidoctor = require('asciidoctor.js')();
var processor = asciidoctor.Asciidoctor(true);

var content = "= This is a title!";
var options = {doctype: 'inline', attributes: ['showtitle']};
var html = processor.convert(content, options);
console.log(html); // returns Opal.nil
```

In the sample above, "This is a title!" is not a candidate for inline conversion and Asciidoctor returns "nil".
## Proposal

Asciidoctor should issue a warning message:

```
No candidate for inline conversion.
Inline document type should be used to convert a single paragraph. If you want to convert a complete document, use the default document type 'article' or simply remove 'doctype' from the options.
Read more about document types: http://asciidoctor.org/docs/user-manual/#document-types
```

I think this warning will help users to understand why the `convert` method returned `nil` (and outline the differences between each document type).

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

File: lib/asciidoctor/document.rb [hunk 1]
```diff
@@ -1047,11 +1047,12 @@ def convert opts = {}
...
 
     if doctype == 'inline'
-      # QUESTION should we warn if @blocks.size > 0 and the first block is not a paragraph?
-      if (block = @blocks[0]) && block.content_model != :compound
-        output = block.content
-      else
-        output = nil
+      if (block = @blocks[0])
+        if block.content_model == :compound || block.content_model == :empty
+          warn %(asciidoctor: WARNING: no inline candidate; use the inline doctype to convert a single paragragh, verbatim, or raw block)
```
Comment (Mogztter) [inline lib/asciidoctor/document.rb]: What do you think about adding a link on the documentation about how to use document types and/or making a suggestion on how to fix it (ie. remove doctype from options) ?

Maybe we should print this information only when verbose is turned on ?

Comment (mojavelinux) [inline lib/asciidoctor/document.rb]: I'm not really a fan of adding links to warning messages. I think Maven tried that and it ended up being very misleading (though it could have been how they did it). I'd actually prefer the user to search because I think it leads them to very valuable information. But that doesn't mean I want to send them on a wild goose chase either. When we resolve #44, we can perhaps assign error codes that would match entries in a table in the documentation. That would get them to an explanation in the least amount of steps.

**Comment by mojavelinux** [comment]
I added some tests.

File: lib/asciidoctor/document.rb (hunk 1 above)
Comment (mojavelinux) [inline lib/asciidoctor/document.rb]: In other words, let's discuss in #44.
