### PR TITLE
resolves #3014 add support for the mute option on vimeo videos

### LINKED ISSUE #3014: Support for the "muted" attribute (Vimeo)
Hello,

First of all, thanks a lot for an awesome tool!

I'm playing around with Vimeo videos and can't make the "autoloop" attribute work. The Vimeo [documentation](https://help.vimeo.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos) says that we need to add the "muted" attribute to the video as well. 

If I add the muted attribute (e.g. video::12345678[vimeo, width=850, height=450, options="muted,autoplay,loop"]), the autoplay doesn't work. Am I missing anything?

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #3014

### CODE REVIEW

File: lib/asciidoctor/converter/html5.rb [hunk 1]
```diff
@@ -981,10 +981,16 @@ def video node
...
           autoplay_param = ''
         end
-        loop_param = (node.option? 'loop') ? %(#{delimiter}loop=1) : ''
+        if node.option? 'loop'
+          loop_param = %(#{delimiter}loop=1)
+          delimiter = '&amp;'
+        else
+          loop_param = ''
+        end
+        mute_param = (node.option? 'mute') ? %(#{delimiter}muted=1) : ''
```
Comment (Mogztter) [inline lib/asciidoctor/converter/html5.rb]: `delimiter` can be undefined here no ?
